version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id: perpetua-data-buffer-144
    private_key_id: 5a8659899849b897ec944507f4f4e2387f1493ce
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDnylyHU3SN5THl\nQYLE4/kQ12p10P/3EJURAyu+3+aKGn4xqbPAcG275J9tN2Q8VZ0m9q4G2ORumxK2\n6lddcxm8RO9gzelDVNNZeMCud+YgHc7fYfMDF9vQpRRu4Nl9H0xSKmqKRuQrD6Fx\nvx4S36Be9XMvQRB9QSNvqWavgkBYavZXtW1XJrEsw3M2Q8UgvgnfckG1dTdk2eA0\nKXwCKqaLuSU2kOEIKt90Qhp1R7ZJqhtjRJXyPKVmal5iI6egUgzlNP8K4BrK2ZEH\nBflYOvULQw4GekCznUBqrEw8Y7RluqoWl3PoL0hQ0qKO4dkbyhVc4ygCE7jVU1Yy\nZdUW9SgxAgMBAAECggEAGmCa+wNyRhuI/A/ic8mFtHbvNI0eM919OTxlJAmS0LCH\nH9uyCvpAYpt30RP2oi8T/TUhRMI17KhVDt/IJWhNy3EE1L1aCEGE86+cLb6TP6Bk\nxGL/JqD2cN34X03TMjv3kXomOaormQLkWm9nWrp8I5JHE1+SIs7g23opp1tpOyZp\nf95tY5ZHNZb9dSgg5EJVIimYlNnsqLMchuakW8ZMZbMyVlm7eh9Fpbku163CxhVM\n+7VC31VtcKSKlHGjYVkEI9ahVx/6u0qPyB04QtRSqbKhkkk/a1SrdHP3mp32+u/R\nHh1xu7J8fNZncswlSlkrGsqaPqBNjsyQhdDLPzw7aQKBgQD6Q2QPXsFXMJKSFmO+\nHCn7tqKAKo8Dju+yIqjpv8ARsjZJPHQLt1sGvqT4pcwbQRHBUK6cMMhyTuNeoH97\n9kA8ep4wcDr9SENyDREXTmErZSdB8N1KtfDYGfwcU0W6Rn8NuUaaoudEd1y5WNts\neOjXLVDqTJJ/2wVZGQKkL6fw4wKBgQDtGpFOhfdGxHB7pzNeQpjQJoVhnyJJ/Q3E\njRpOfIqRJH372L7sqXvBvuv+JqYnXJ8cmGDjbHQat+WggOVTld9fhkw2I2vde9Bw\nB7iYKw7NxGhv2sBB98Qz08NWv0E1eWm+ExWtOeCwUwLXhsXSFexiF3wZjmxqOz6Q\nwTG5yvdy2wKBgAhrjglKWdzyIGxT3oU981epvGvtgqRPAdePfPloXzD5OwRZyVm/\nkIt4jJplEan1FYDYkxdkOMpHxzSe18s27NBcG8hrbkCpVsOWlvWeyHwqShjY3skt\nt+29ahMV5imvR4URr8NyKa/PCEqgJ7nNk5/xwWAwtVkh6FsoEUOu6sqbAoGBAIbU\nmNTicZ+Yja6Dgj6T+HpFrYu6BrG0aWPgKZmAUPwAmHPi6Y+DQZEHlQPNzqaLkR+d\nt1scjVm0QaxoIADMNV4I7MXMlsY4ZmuOuHYv5hc1HX6eEr5wuu4N+gMWd2qFRJCG\nIcmEJDWgvvj49v1k4itV14hg6V3vmsCOXEyfEuAJAoGBAOfDE9gjoniWsLPTNr1R\neyOv2zGq0yDuNSlsbm9JqUkAs6Tpz0+cBwXNfWATSKia+KAhFDEMnkKYHSIQUen5\ncUtVOx5yKSBWWHEMU6YrFXMMYwYSbtwEwth92zWE6UI0bPyoRL1OV/j6BT4r0WuT\nAWe8NrEPHLNr54zTq/I+DeKB\n-----END PRIVATE KEY-----"
    client_email: mageai-to-bq@perpetua-data-buffer-144.iam.gserviceaccount.com
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/mageai-to-bq%40perpetua-data-buffer-144.iam.gserviceaccount.com"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: 
  GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
